[workspace]
resolver = "2"
members = ["crates/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
rand = "0.8.5"
rayon = "1.8.0"
zmq = "0.10.0"
flatbuffers = "23.5.26"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"