[package]
name = "ml-inference"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zmq = "0.10.0"
rand = "0.8.5"
flatbuffers = "23.5.26"
rayon = "1.8.0"